name: Software

on:
  push:
    branches: [ main ]
    paths: [src/input_software/**]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install libs
      working-directory: ./src/input_software
      run: pip3 install -r ./reqs.txt
    - name: Install PyInstaller
      run: pip3 install pyinstaller
    - name: Build App Using PyInstaller
      working-directory: ./src/input_software
      run: pyinstaller --one-file main.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Artifact
        path: ./src/input_software/dist
