name: Upload ZIP

on:
  push:
    branches: [ main ]
    paths: [src/camera_software/**]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Upload a artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Archive
          path: ./src/camera_software/src
        
